### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by huan** [JsCommunity/json-rpc-peer#50]
I think we should also convert the code base of this module from JavaScript to TypeScript too because we had already done JsonRpcProtocol: <https://github.com/JsCommunity/json-rpc-protocol/issues/30>

**Comment by julien-f** [comment]
Like list time, I'm open to a PR :slightly_smiling_face:

**Comment by zixia** [comment]
Ok, like list time, I'll make it. :)

**Comment by zixia** [comment]
Hi @julien-f, 

Good weekend. 

I had submitted a PR(#56) that convert the code base to the TypeScript, please have a look when you have time.

Thanks.

**Comment by zixia** [comment]
ping @julien-f

**Comment by julien-f** [comment]
Hi,

I've seen your PR but I have very little time between my job and the holidays, I'll have more time in a couple of months.

If you really are in a hurry, you can publish a temp fork on npm :slightly_smiling_face:

**Comment by zixia** [comment]
No, I'm not in a hurry, no rush at all.

Just want to confirm that this issue has not been forgotten, and please take your time and feel free to let me know if I need to something.

BTW: I'd like be a volunteer to help you maintain the json-rpc projects when you need any collaborator.

**Comment by zixia** [comment]
@julien-f Did you get time to review this PR for now? :)

**Comment by maxhawkins** [comment]
I'd love to see this merged!

**Comment by maxhawkins** [comment]
I added a PR that adds typescript definitions rather than converting the project to typescript
